version: '3.1'

services:
  wordpress:
    build: ./docker/wordpress/
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./html:/var/www/html
      - ./docker/wordpress/wp-install.sh:/tmp/wp-install.sh

  db:
    build: ./docker/db/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/var/lib/mysql:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/db/var/log/mysql:/var/log/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: test
      PMA_PASSWORD: test
    ports:
      - 3000:80

  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    depends_on:
      - wordpress
